name: Build

on:
  release:
    types:
      - published

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - darwin
          - windows
          - linux
        goarch:
          - amd64
          - arm64

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build
        run: go build -o csv2ics cmd/csv2ics.go

      - name: Release file
        uses: djnicholson/release-action@v2.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-name: ${{ github.event.release.name }}
          tag-name: ${{ github.event.release.tag_name }}
          asset-name: csv2ics-${{ matrix.goos }}-${{ matrix.goarch }}
          file: csv2ics
